<?php

namespace AppBundle\Repository;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findbyanswer($lid,$qid,$uid){
        return $this->getEntityManager()
            ->createQuery(
        'SELECT  a FROM AppBundle:Answer a WHERE a.qId = :qid And a.lId=:lid AND a.uId=:uid'
        )->setParameter('qid', $qid)
         ->setParameter('lid', $lid)
         ->setParameter('uid', $uid)
         ->setMaxResults(1)->getOneOrNullResult();
    }
}
