<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends EntityRepository
{
    public function listcontent(){
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT  l.lId,c.cId,c.cTitle,c.cNote,c.cImg,c.cVideo,l.lTitle FROM AppBundle:Content c INNER JOIN AppBundle:Lesson l  '
                . 'With  c.lId= l.lId Order By l.lId'
            );        
        return $query->getResult();
    }
    
    public function listcontent2(){
        $les_arr = array();
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT  l.lId,l.lTitle FROM AppBundle:Lesson l'
            );        
        $lessons = $query->getResult();
        foreach  ($lessons as $lesson){
            $data = array();
            $data['lid'] = $lesson['lId'];
            $data['ltitle'] = $lesson['lTitle'];
            
            $query2 = $em->createQuery(
            'SELECT  c.cId,c.cTitle,c.cNote,c.cImg,c.cVideo FROM AppBundle:Content c Where c.lId = ' . $lesson['lId']
            );  
            $contents = $query2->getResult();
            $con_arr = array();
            foreach ($contents as $content){
                array_push($con_arr, $content);
            }
            $data['content'] = $con_arr;
            array_push($les_arr, $data);
        }
        return $les_arr;
    }
}
