<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{
    public function listcourse(){
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT  cou.uId,u.uName,cou.couId,cou.couName FROM AppBundle:Course cou INNER JOIN AppBundle:User u  '
                . 'With  u.uId= cou.uId '
            );        
        return $query->getResult();
    }
}
