<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * LessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonRepository extends EntityRepository
{
    public function listlesson(){
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT  cou.couId,cou.couName,l.lId,l.lTitle FROM AppBundle:Lesson l INNER JOIN AppBundle:Course cou  '
                . 'With  l.couId= cou.couId Order By cou.couId'
            );        
        return $query->getResult();
    }
}
