<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findByMail($email)
    {
        return $this->getEntityManager()
            ->createQuery(
        'SELECT u
        FROM AppBundle:User u
        WHERE u.uEmail = :email'
        )->setParameter('email', $email)
         ->setMaxResults(1)->getOneOrNullResult();
    }
    
    public function checkmailalreadyexist($email,$id)
    {
        return $this->getEntityManager()
            ->createQuery(
        'SELECT u
        FROM AppBundle:User u
        WHERE u.uEmail = :email And u.uId != :id'
        )->setParameter('email', $email)
         ->setParameter('id', $id)
         ->setMaxResults(1)->getOneOrNullResult();
    }
    
    public function checkusernamealreadyexist($email,$id)
    {
        return $this->getEntityManager()
            ->createQuery(
        'SELECT u
        FROM AppBundle:User u
        WHERE u.uEmail = :email And u.uId != :id'
        )->setParameter('email', $email)
         ->setParameter('id', $id)
         ->setMaxResults(1)->getOneOrNullResult();
    }
    
    
    public function findById($id)
    {
        return $this->getEntityManager()
            ->createQuery(
        'SELECT u
        FROM AppBundle:User u
        WHERE u.uId = :id'
        )->setParameter('id', $id)
         ->setMaxResults(1)->getOneOrNullResult();
    }

    public function listuser(){
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT u.uId,u.uName,u.uUserName,u.uPhone,u.uEmail,u.uAddress,u.uGender,u.uDOB,u.uRole,ur.rName,u.uActive
             FROM AppBundle:User u INNER JOIN AppBundle:UserRole ur  With ur.rId=u.uRole Where u.uActive=1 '
            );        
        return $query->getResult();
    }


    public function listbyrole($urole,$searchtxt){
        $q = 'SELECT u.uId,u.uName,u.uUserName,u.uPhone,u.uEmail,u.uAddress,u.uGender,u.uDOB,u.uRole,u.uActive
             FROM AppBundle:User u Where u.uActive=1 AND u.uRole=' . $urole ;
        if ($searchtxt!=''){
            $searchtxt = '%' . $searchtxt . '%';
            $searchtxt = "'" . $searchtxt . "'";
            $q = $q . ' AND (Trim(u.uName) Like ' . $searchtxt .
                ' OR Trim(u.uUserName) Like ' . $searchtxt .
                ' OR Trim(u.uPhone) Like  ' . $searchtxt . 
                ' OR Trim(u.uEmail) Like ' . $searchtxt . ')';
        }
        $em = $this->getEntityManager();
        $query = $em->createQuery($q);        
        return $query->getResult();
    }
}
